package shared;

public enum MessageOperation
{
    LOGIN,
    ADDTRADEITEM,
    REMOVETRADEITEM,
    ACCEPTTRADE,
    REGISTERPROPERTY,
    SUBSCRIBETOPROPERTY,
    UNSUBSCRIBEFROMPROPERTY,
    UPDATEPROPERTY

}
