package shared;

public enum MessageOperation
{
    ADDTRADEITEM,
    REMOVETRADEITEM,
    ACCEPTTRADE,
    TRADEITEMS,
    REGISTERPROPERTY,
    UNREGISTERPROPERTY,
    SUBSCRIBETOPROPERTY,
    UNSUBSCRIBEFROMPROPERTY,
    UPDATEPROPERTY //Kan misschien wel gewoon weg

}
