package Enums;

public enum MessageOperation
{
    ADDTRADEITEM,
    REMOVETRADEITEM,
    ACCEPTTRADE,
    TRADEITEMS,
    REGISTERPROPERTY,
    UNREGISTERPROPERTY,
    SUBSCRIBETOPROPERTY,
    UNSUBSCRIBEFROMPROPERTY

}
